status_by_code = {  
    100:'Continue («продолжайте»)',
    101: 'Switching Protocols («переключение протоколов»)',
    102: 'Processing («идёт обработка»)',
    103: 'Early Hints («предварительный ответ»)',
    200: 'OK (хорошо)',
    201: 'Created (создано)',
    202: 'Accepted (принято)',
    203: 'Non-Authoritative Information (информация не авторитетна)',
    204:'No Content (нет содержимого)',
    205: 'Reset Content (сбросить содержимое)',
    206: 'Partial Content (частичное содержимое)',
    207: 'Multi-Status (многостатусный)',
    208: 'Already Reported (уже сообщалось)',
    226: 'IM Used (использовано IM)',
    400: 'Bad Request («неправильный, некорректный запрос»)',
    401: 'Unauthorized («не авторизован»)',
    402: 'Payment Required («необходима оплата») — зарезервировано для использования в будущем',
    403: 'Forbidden («запрещено (не уполномочен)»)',
    404: 'Not Found («не найдено»)',
    405: 'Method Not Allowed («метод не поддерживается»)',
    406: 'Not Acceptable («неприемлемо»)',
    500: 'Internal Server Error («внутренняя ошибка сервера»)',
    501: 'Not Implemented («не реализовано»)',
    502: 'Bad Gateway («плохой, ошибочный шлюз»)',
    503: 'Service Unavailable («сервис недоступен»)',
    504: 'Gateway Timeout («шлюз не отвечает»)'
}